"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type Guide = { company: string; group: "Big Tech" | "Product" | "Enterprise" | "Finance"; color: string; focus: string; keywords: string[]; proof: string; source: string };

const GUIDES: Guide[] = [
  { company: "Google", group: "Big Tech", color: "#4285F4", focus: "Show role-relevant technical depth, problem solving, leadership and impact at scale.", keywords: ["scalability", "experimentation", "cross-functional"], proof: "Improved search latency 32% for 4M monthly queries by redesigning the caching layer.", source: "https://www.google.com/about/careers/applications/" },
  { company: "Amazon", group: "Big Tech", color: "#FF9900", focus: "Write metric-rich bullets that reveal ownership, customer obsession and decisive delivery.", keywords: ["ownership", "customer", "metrics"], proof: "Owned checkout recovery project, reducing failed orders 18% and recovering $1.2M ARR.", source: "https://www.amazon.jobs/content/en/how-we-hire" },
  { company: "Microsoft", group: "Big Tech", color: "#00A4EF", focus: "Connect your experience to customer impact, collaboration, adaptability and a growth mindset.", keywords: ["collaboration", "customer impact", "growth mindset"], proof: "Aligned 4 teams on a migration plan that cut support incidents 41% without downtime.", source: "https://careers.microsoft.com/v2/global/en/hiring-tips" },
  { company: "Meta", group: "Big Tech", color: "#0866FF", focus: "Prioritize shipped products, fast execution, analytical decisions and impact at large scale.", keywords: ["product impact", "scale", "execution"], proof: "Shipped ranking experiment to 8M users, increasing meaningful interactions 9.4%.", source: "https://www.metacareers.com/careerprograms/" },
  { company: "Apple", group: "Big Tech", color: "#A3AAAE", focus: "Highlight craft, user experience, privacy, hardware-software collaboration and attention to detail.", keywords: ["quality", "privacy", "user experience"], proof: "Reduced app launch time 38% while meeting accessibility and on-device privacy requirements.", source: "https://www.apple.com/careers/us/" },
  { company: "Netflix", group: "Product", color: "#E50914", focus: "Demonstrate independent judgment, candid collaboration and high-impact decisions with context.", keywords: ["judgment", "ownership", "innovation"], proof: "Reframed a costly roadmap bet using cohort data, saving 6 engineer-months.", source: "https://jobs.netflix.com/culture" },
  { company: "NVIDIA", group: "Big Tech", color: "#76B900", focus: "Lead with deep technical expertise, accelerated computing outcomes and research or patent evidence.", keywords: ["GPU", "performance", "AI systems"], proof: "Optimized CUDA kernels to deliver 2.7× faster inference at 23% lower memory use.", source: "https://www.nvidia.com/en-us/about-nvidia/careers/" },
  { company: "Tesla", group: "Product", color: "#E82127", focus: "Use concise evidence of first-principles problem solving, speed and hands-on engineering.", keywords: ["first principles", "manufacturing", "automation"], proof: "Automated end-of-line validation, cutting cycle time 26% across 3 production cells.", source: "https://www.tesla.com/careers" },
  { company: "Adobe", group: "Enterprise", color: "#FA0F00", focus: "Balance creative-product empathy with measurable subscription, AI or platform results.", keywords: ["creativity", "customer experience", "platform"], proof: "Redesigned onboarding journey, lifting first-week activation 14% across 120K creators.", source: "https://careers.adobe.com/us/en" },
  { company: "Salesforce", group: "Enterprise", color: "#0D9DDA", focus: "Show customer success, trusted systems, business value and effective stakeholder leadership.", keywords: ["customer success", "CRM", "trust"], proof: "Led CRM consolidation for 6 regions, improving forecast accuracy from 71% to 89%.", source: "https://careers.salesforce.com/en/how-we-hire/" },
  { company: "Uber", group: "Product", color: "#E2E8F0", focus: "Feature marketplace thinking, operations at scale and data-backed product or engineering wins.", keywords: ["marketplace", "operations", "experimentation"], proof: "Rebalanced driver incentives in 2 cities, reducing rider wait time 11% within budget.", source: "https://www.uber.com/us/en/careers/" },
  { company: "Airbnb", group: "Product", color: "#FF5A5F", focus: "Connect technical or business outcomes to belonging, trust, design quality and host/guest needs.", keywords: ["community", "trust", "design"], proof: "Built trust signals that reduced booking cancellations 16% for first-time guests.", source: "https://careers.airbnb.com/" },
  { company: "Atlassian", group: "Enterprise", color: "#2684FF", focus: "Emphasize open teamwork, distributed collaboration and tools that improve team effectiveness.", keywords: ["teamwork", "distributed", "developer tools"], proof: "Introduced async RFC workflow, reducing cross-time-zone decision time from 5 days to 2.", source: "https://www.atlassian.com/company/careers" },
  { company: "Stripe", group: "Product", color: "#635BFF", focus: "Show rigorous API or systems work, economic impact, clear writing and care for developer experience.", keywords: ["APIs", "reliability", "economic impact"], proof: "Simplified payment API integration, cutting median merchant setup from 3 days to 4 hours.", source: "https://stripe.com/jobs/culture" },
  { company: "Goldman Sachs", group: "Finance", color: "#7399C6", focus: "Combine analytical rigor, risk awareness, client outcomes and leadership under pressure.", keywords: ["risk", "analysis", "client impact"], proof: "Automated risk reconciliation for a $2.4B portfolio, saving 18 analyst-hours weekly.", source: "https://www.goldmansachs.com/careers" },
];

const GROUPS = ["All", "Big Tech", "Product", "Enterprise", "Finance"] as const;

export default function CompanyGuidesPage() {
  const [query, setQuery] = useState("");
  const [group, setGroup] = useState<(typeof GROUPS)[number]>("All");
  const filtered = useMemo(() => GUIDES.filter((guide) => (group === "All" || guide.group === group) && `${guide.company} ${guide.focus} ${guide.keywords.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [query, group]);

  return <main className="min-h-screen bg-[#080c14] text-white">
    <section className="relative overflow-hidden border-b border-white/[0.06] px-5 py-20"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(124,58,237,.18),transparent_55%)]" /><div className="relative mx-auto max-w-5xl text-center"><p className="mb-4 text-xs font-bold uppercase tracking-[0.25em] text-violet-400">Company Resume Guide</p><h1 className="text-4xl font-extrabold tracking-tight sm:text-6xl">Tailor your resume for<br/><span className="text-violet-400">where you want to work.</span></h1><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-gray-400">15 focused playbooks based on public company hiring and culture materials. Use them as tailoring prompts—not as a guarantee of selection.</p><div className="mx-auto mt-8 flex max-w-2xl flex-col gap-3 sm:flex-row"><input aria-label="Search company guides" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search company, skill, or keyword…" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/[0.05] px-4 py-3 text-sm outline-none placeholder:text-gray-600 focus:border-violet-500"/><Link href="/builder" className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-bold hover:bg-violet-500">Open Resume Builder →</Link></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-12"><div className="mb-8 flex flex-wrap gap-2">{GROUPS.map((item) => <button key={item} onClick={() => setGroup(item)} className={`rounded-full border px-4 py-2 text-xs font-semibold transition ${group === item ? "border-violet-500 bg-violet-500/20 text-violet-300" : "border-white/10 text-gray-400 hover:border-white/20"}`}>{item}</button>)}<span className="ml-auto self-center text-xs text-gray-600">{filtered.length} guides</span></div>
      <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((guide) => <article key={guide.company} className="group rounded-2xl border border-white/[0.08] bg-white/[0.025] p-6 transition hover:-translate-y-0.5 hover:border-violet-500/35"><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl text-sm font-black text-[#080c14]" style={{backgroundColor: guide.color}}>{guide.company.slice(0,2).toUpperCase()}</span><div><h2 className="font-bold">{guide.company}</h2><p className="text-xs text-gray-500">{guide.group}</p></div></div><a href={guide.source} target="_blank" rel="noreferrer" aria-label={`${guide.company} careers source`} className="text-xs text-gray-500 hover:text-violet-300">Official source ↗</a></div><p className="min-h-16 text-sm leading-6 text-gray-300">{guide.focus}</p><div className="my-5 flex flex-wrap gap-2">{guide.keywords.map((word) => <span key={word} className="rounded-md bg-white/[0.05] px-2 py-1 text-[11px] text-gray-400">{word}</span>)}</div><div className="rounded-xl border border-emerald-500/15 bg-emerald-500/[0.05] p-4"><p className="mb-1 text-[10px] font-bold uppercase tracking-wider text-emerald-400">Achievement pattern</p><p className="text-xs leading-5 text-gray-300">“{guide.proof}”</p></div></article>)}</div>
      {filtered.length === 0 && <div className="py-20 text-center text-gray-500">No guide matches that search.</div>}<div className="mt-10 rounded-2xl border border-amber-500/20 bg-amber-500/[0.05] p-5 text-sm leading-6 text-gray-400"><strong className="text-amber-300">How to use these guides:</strong> open the current job description, mirror only skills you genuinely have, and replace the example bullet with your own action, scope and measured result. Company expectations vary by role, level, team and location.</div>
    </section>
  </main>;
}
